linters:
  enable:
    - gosimple
    - staticcheck
    - govet

    - asciicheck
    - errcheck
    - errorlint
    - gofmt
    - goimports
    - gosec
    #    - gocritic
    - importas
    #    - prealloc
    - revive
    - misspell
    - stylecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
