name: golangci-lint
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  golangci:
    name: GO lang CI linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2 # https://github.com/marketplace/actions/run-golangci-lint
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.43
          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0
